### PR TITLE
Add WAPdB python scraper

### PR DESCRIPTION
**Pull request by Releck**
Adds a scraper for warashi asian pornstars (WAPdB).

Notes:
- Tested on over 100 female profiles and a dozen male ones.
- French/Japanese return partial data as some data is in raw `<p>` tags which were processed in English.
- I could only find one mini profile that had AV activity listed and it was unknown so it isn't supported.
- Characteristics like piercing and tattoos are checked twice as they are sometimes present only in the "distinctive physical characteristics" field or tags
- Some pages will return the default picture. These pictures use the same URL path as the normal ones and there's no way to tell which ones these are. My guess is these were manually changed.
- Some performers have multiple twitter handles listed. This scraper returns the first one.
- Tested on python 3.10 but should work on 3.8 and up. Requires requests and beautifulsoup.

### CODE REVIEW

**Comment by Belleyy** [comment]
```
ERRO[2022-01-14 18:04:07] [Scrape / WAPdB]     performer['measurements'] = measurements_node.text.split(measurements_prefix)[1]
ERRO[2022-01-14 18:04:07] [Scrape / WAPdB]   File "C:\Users\Winter\AppData\Local\Programs\Python\Python39\lib\site-packages\bs4\element.py", line 921, in __getattr__
ERRO[2022-01-14 18:04:07] [Scrape / WAPdB]     raise AttributeError(
ERRO[2022-01-14 18:04:07] [Scrape / WAPdB] AttributeError: 'NavigableString' object has no attribute 'text'
```
So i got this error (Tested on Fukada Eimi & Sora Shiina).
Removing the `.text` no longer create this error. (For `measurements` & `career_length`)

**Comment by Releck** [comment]
Tested both those performers and they both work without any changes. What version of beautifulsoup are you using? I tested with 4.10.0.

**Comment by Belleyy** [comment]
I'm using the v4.9.3 for bs4 and python v3.9.1

**Comment by bnkai** [comment]
4.10 has this 
```
* NavigableString and its subclasses now implement the get_text()
  method, as well as the properties .strings and
  .stripped_strings. These methods will either return the string
  itself, or nothing, so the only reason to use this is when iterating
  over a list of mixed Tag and NavigableString objects. [bug=1904309]
```
so we would need to add a comment to the import requiring version 4.10
or change the code to  work with older versions eg
use  `findAll` instead of `find` and iterate through eache result keeping the first non `NavigableString`  one using `isInstance`

For obvious reasons i would just add a comment for the version

File: scrapers/WAPdB.py [hunk 1]
```diff
@@ -0,0 +1,222 @@
...
+        if image_node := image_container_node.find('img', {'itemprop': 'image'}):
+            image_url = image_node.attrs['src']
+            if '/WAPdB-img/par-defaut/' not in image_url:
+                performer['image'] = f'http://warashi-asian-pornstars.fr{image_url}'
+
+    if len(country_nodes := soup.find_all('span', {'itemprop': 'addressCountry'})) > 1:
+        country = country_nodes[1].text
+        performer['country'] = country
+        if country == 'Japan':
+            performer['ethnicity'] = 'Japanese'
```
Comment (bnkai) [inline scrapers/WAPdB.py:137]: for ethnicity we use `asian` 
i think its safe to use it as a fixed value insteas as all the performers in the site are asians ?

File: scrapers/WAPdB.py [hunk 2]
```diff
@@ -0,0 +1,222 @@
...
+        if birthplace_node := details_node.find('p', text=lambda t: birthplace_prefix in str(t)):
+            birthplace_full = birthplace_node.text.split(birthplace_prefix)[1]
+            if ', ' in birthplace_full:
+                birthplace = birthplace_full.split(', ')[0]
+            else:
+                birthplace = birthplace_full
+            if birthplace != 'unknown':
+                performer['country'] = birthplace
+            if birthplace == 'Japan':
+                performer['Ethnicity'] = 'Japanese'
```
Comment (bnkai) [inline scrapers/WAPdB.py:77]: same here
for ethnicity we use `asian` 
i think its safe to use it as a fixed value insteas as all the performers in the site are asians ?

**Comment by bnkai** [comment]
the birthplace/country seems to be missing from the full profile?

File: scrapers/WAPdB.py (hunk 1 above)
Comment (Releck) [reply scrapers/WAPdB.py:137]: Wasn't sure what the convention was as "asian" where I'm from means people from the Indian subcontinent. There are some American and French performers on the site so it's not safe to make it a static value.

**Comment by Releck** [comment]
> the birthplace/country seems to be missing from the full profile?

Can you give some examples? Some full profiles don't list the country (Satou Haruki) but others that list them (Tachibana Nao) are picked up.

**Comment by bnkai** [comment]
> > the birthplace/country seems to be missing from the full profile?
> 
> Can you give some examples? Some full profiles don't list the country (Satou Haruki) but others that list them (Tachibana Nao) are picked up.
Yeah i'll have to find the performers i tested :-( I will let you know
What happened from what i remember was the country was not updated even though the birth place was available. I'll update when i have the performers.

File: scrapers/WAPdB.py (hunk 1 above)
Comment (bnkai) [reply scrapers/WAPdB.py]: Yeah the `asian performers database` in the title made me think that...

**Comment by bnkai** [comment]
Update:
I can't seem to find the performer cases mentioned above, everything seems ok
Ok to merge @Releck  ?

**Comment by Releck** [comment]
I've added a check that should make it clearer for users if beautifulsoup is out of date. If you're happy with that feel free to merge @bnkai.
